version: '3'
services:
#  service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "6060:6060"
#    entrypoint:
#      - /bin/bash
#      - -c
#      - java -jar /app/auth-*.jar
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - freddy-ai-bridge
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - freddy-ai-bridge

  opensearch-node1:
    image: opensearchproject/opensearch:2.5.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true" # Disables security plugin
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: [ "CMD", "curl", "-XGET", "https://localhost:9200", "-u", "'admin:admin'", "--insecure" ]
      interval: 5s
      timeout: 5s
      retries: 60
    ports:
      - 9200:9200
      - 9600:9600
    expose:
      - "9200"
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"

networks:
  freddy-ai-bridge:
    driver: bridge
